BASIC:
  SEED: 26
  BACKUP_CODES: True
  BACKUP_LIST: ['lib', 'tools_cam', 'configs']

MODEL:
  ARCH: vgg16_cam
  CAM_THR: 0.1
  TOP_K: 1

DATA:
  DATASET: CUB
  DATADIR: /data1/CUB/cub_200_2011/CUB_200_2011
  NUM_CLASSES: 200
  RESIZE_SIZE : 256
  CROP_SIZE : 224
  IMAGE_MEAN : [0.485, 0.456, 0.406]
  IMAGE_STD : [0.229, 0.224, 0.225]

TRAIN:
  BATCH_SIZE: 64

TEST:
  BATCH_SIZE: 2 #64 #32 #128
  SAVE_BOXED_IMAGE: False

SOLVER:
  START_LR: 0.001
  LR_STEPS: [12, 24,]
  NUM_EPOCHS: 40
  LR_FACTOR: 0.1
  MUMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True