BASIC:
  SEED: 26
  BACKUP_CODES: True
  BACKUP_LIST: ['lib', 'tools_cam', 'configs']
  SMOOTHING: 0.1
MODEL:
  ARCH: deit_trt_fuse_base_patch16_224 
  CAM_THR: 0.1
  TOP_K: 1
  THRESH: 0.95

DATA:
  DATASET: ImageNet
  DATADIR: /data1/ImageNet/ImageNet_ILSVRC2012
  NUM_CLASSES: 1000
  RESIZE_SIZE : 256
  CROP_SIZE : 224
  IMAGE_MEAN : [0.485, 0.456, 0.406]
  IMAGE_STD : [0.229, 0.224, 0.225]

TRAIN:
  BATCH_SIZE: 512 #128

TEST:
  BATCH_SIZE: 512 #128
  SAVE_BOXED_IMAGE: False

SOLVER:
  START_LR: 0.001
  LR_STEPS: [2,4,6,8]
  NUM_EPOCHS: 12
  LR_FACTOR: 0.4
  MUMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True
